name: Commit Success-Check

on:
  schedule:
    - cron: '25 4 * * *' # Schedule for daily run at midnight Singpapore Time

jobs:
  commit-success:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository with Token
      if: github.ref == 'refs/heads/main'
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }} 

    - name: Create SUCCESS.txt
      run: echo "SUCCESS" >> ${{ github.workspace }}/CICD-Tooling/github-actions/SUCCESS.txt

    - name: Commit SUCCESS Status
      run: |
        git config user.email ${{ secrets.GIT_USER_EMAIL }}
        git config user.name "Coolbreeze151"
        git add ${{ github.workspace }}/CICD-Tooling/github-actions/SUCCESS.txt
        git commit -m "Add Dependency-Check JSON report"
        git push origin HEAD:main

