name: OWASP Dependency-Check

on:
  push:
    branches:
      - main
  schedule:
    - cron: '20 5 * * *' # Schedule for daily run at midnight

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository with Token
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }} 

    - name: Create SUCCESS.txt
      run: echo "Commit date: $(date)" > ${{ github.workspace }}/github-actions/SUCCESS.txt

    - name: Commit JSON Report
      run: |
        git config user.email ${{ secrets.GIT_USER_EMAIL }}
        git config user.name "Coolbreeze151"
        git add ${{ github.workspace }}/github-actions/SUCCESS.txt
        git commit -m "Add Dependency-Check JSON report"
        git push origin HEAD:main

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ${{ github.workspace }}/github-actions/dependency-check-report.json


