name: OWASP Dependency-Check

on:
  push:
    branches:
      - main

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Specify the Java version you want to use
        distribution: 'adopt'  # Specify the distribution (e.g., 'adopt', 'adopt-lts', 'corretto', 'zulu', etc.)

    - name: Run OWASP Dependency-Check
      run: |
        curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v7.3.0/dependency-check-7.3.0-release.zip
        unzip dependency-check-7.3.0-release.zip
        chmod +x dependency-check/bin/dependency-check.sh
        ./dependency-check/bin/dependency-check.sh --project "Your Project Name" --scan /path/to/your/project --out /tmp --format ALL
      env:
        MAVEN_OPTS: -Dmaven.repo.local=${{ runner.workspace }}/.m2/repository
        MVNW_HOME: ./mvnw

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: /tmp/dependency-check-report.json
